[file]
"caster alias file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data\\sm_aliases.toml"
"caster bring me file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\sm_bringme.toml"
"caster chain aliases file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data\\sm_chain_aliases.toml"
"caster clipboard file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data\\clipboard.json"
"caster companion file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\companion_config.toml"
"caster hooks file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\hooks.toml"
"caster log file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data\\log.txt"
"caster record from history file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data\\sm_history.toml"
"caster rules file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\rules.toml"
"caster settings file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\settings.toml"
"caster transformer file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\transformers\\words.txt"
"caster transformers file" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings\\transformers.toml"

[folder]
"caster data" = "C:\\Users\\dusty\\AppData\\Local\\caster\\data"
"caster hooks" = "C:\\Users\\dusty\\AppData\\Local\\caster\\hooks"
"caster rules" = "C:\\Users\\dusty\\AppData\\Local\\caster\\rules"
"caster settings" = "C:\\Users\\dusty\\AppData\\Local\\caster\\settings"
"caster transformers" = "C:\\Users\\dusty\\AppData\\Local\\caster\\transformers"
"caster user" = "C:\\Users\\dusty\\AppData\\Local\\caster"
"libraries | home" = "C:\\Users\\dusty"
"my documents" = "C:\\Users\\dusty\\Documents"
"my pictures" = "C:\\Users\\dusty\\Pictures"
"sick you lee" = "C:\\Users\\dusty\\AppData\\Local\\caster\\sikuli"

[program]
DragonPad = "C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program\\natspeak.exe"
"Visual Studio code" = "C:\\Program Files\\Microsoft VS Code\\Code.exe"
chrome = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
messenger = "C:\\Program Files\\WindowsApps\\FACEBOOK.317180B0BB486_460.16.123.0_x64__8xx8rvfyw5nnt\\app\\Messenger.exe"
notepad = "C:\\Windows\\notepad.exe"
wire = "C:\\Users\\dusty\\AppData\\Local\\wire\\app-3.16.3562\\Wire.exe"

[website]
calendar = "https://calendar.google.com/calendar/b/1/r"
"caster discord" = "https://discord.gg/9eAAsCJr"
"caster documentation" = "https://caster.readthedocs.io/en/latest/"
"caster gitter" = "https://gitter.im/dictation-toolbox/Caster"
"dragonfly documentation" = "https://dragonfly2.readthedocs.io/en/latest/"
"dragonfly gitter" = "https://gitter.im/dictation-toolbox/dragonfly"
facebook = "https://www.facebook.com"
google = "https://www.google.com"
male = "http://mail.phillips.codes"
"tick tick" = "https://ticktick.com/#q/all/tasks"
"writing excuses" = "https://writingexcuses.com/"
